## Import Neccessary Packages

In [2]:
!pip install Dash

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 55.5 MB/s eta 0:00:00


In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [5]:
# Load the dataset
from google.colab import files
uploaded = files.upload()


Saving sample_audit_data.csv to sample_audit_data.csv


In [9]:
 data = pd.read_csv('sample_audit_data.csv')

 print(data)

     Unnamed: 0  company_id industry_code       revenue  total_assets  \
0             0           1             D  1.054697e+06  5.298753e+06   
1             1           2             E  1.362883e+06  4.248209e+06   
2             2           3             C  1.240505e+06  4.573642e+06   
3             3           4             E  1.111942e+06  6.148446e+06   
4             4           5             E  6.047628e+05  5.113270e+06   
..          ...         ...           ...           ...           ...   
995         995         996             B  2.184046e+05  3.862314e+06   
996         996         997             A  1.441555e+06  4.798508e+06   
997         997         998             A  9.610814e+05  4.993479e+06   
998         998         999             D  9.097600e+05  5.598794e+06   
999         999        1000             C  2.596554e+06  5.668340e+06   

     current_ratio  debt_to_equity_ratio  inventory_turnover  \
0         1.132913              0.704259            6.14602

In [7]:
# Data Preprocessing
# Handle missing values
data.fillna(0, inplace=True)

In [8]:
# Encode categorical variables (industry_code, risk_level)
label_encoder = LabelEncoder()
data['industry_code_encoded'] = label_encoder.fit_transform(data['industry_code'])
data['risk_level_encoded'] = label_encoder.fit_transform(data['risk_level'])

In [15]:
# Drop unnecessary columns
X = data.drop(['company_id', 'audit_findings', 'risk_level', 'previous_year_risk_level', 'industry_code', 'risk_level'], axis=1)
y = data['risk_level']

In [16]:
# Split the dataset into train and test sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
# Model Training: Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)


RandomForestClassifier(random_state=42)

In [19]:
# Model Predictions
y_pred = model.predict(X_test_scaled)

In [20]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nAccuracy Score:", accuracy_score(y_test, y_pred))


Confusion Matrix:
[[  0  16   2]
 [  1 104   6]
 [  0  70   1]]

Classification Report:
              precision    recall  f1-score   support

        High       0.00      0.00      0.00        18
         Low       0.55      0.94      0.69       111
      Medium       0.11      0.01      0.03        71

    accuracy                           0.53       200
   macro avg       0.22      0.32      0.24       200
weighted avg       0.34      0.53      0.39       200


Accuracy Score: 0.525
